import numpy as np

ntu60_motion_descriptions = {
    "drink water": "Lifting hand towards mouth, tilting the wrist to drink.",
    "eat meal": "Bending arm to bring food to mouth, performing chewing motion.",
    "brush teeth": "Circular movement of the hand with a toothbrush on the teeth.",
    "brush hair": "Moving a brush through hair, typically with a back-and-forth motion.",
    "drop": "Letting an object fall from the hand, with downward motion.",
    "pick up": "Bending down or reaching to grasp an object.",
    "throw": "Swinging arm in a forward motion to release an object.",
    "sit down": "Lowering body to sit, bending knees and hips.",
    "stand up": "Rising from a seated position, extending legs and pushing with arms.",
    "clapping": "Bringing both hands together in a rhythmic motion.",
    "reading": "Turning pages or scrolling with hand movements.",
    "writing": "Moving a pen or pencil across a surface, with a hand-gliding motion.",
    "tear up paper": "Grabbing and pulling paper apart with hands.",
    "put on jacket": "Sliding arms into sleeves, adjusting the jacket over the body.",
    "take off jacket": "Removing arms from sleeves, pulling jacket off shoulders.",
    "put on shoe": "Bending down, placing feet into shoes, and adjusting.",
    "take off shoe": "Sliding feet out of shoes, typically in an upward motion.",
    "put on glasses": "Lifting glasses and placing them on the face.",
    "take off glasses": "Removing glasses from the face, pulling them away from eyes.",
    "put on hat or cap": "Placing hat on the head, adjusting it.",
    "take off hat or cap": "Removing hat from the head, lifting it off.",
    "cheer up": "Raising arms or clapping, with a broad smile or expression.",
    "hand waving": "Moving hand back and forth in a waving motion.",
    "kicking something": "Lifting leg and striking an object with the foot.",
    "reach into pocket": "Extending arm and hand into the pocket to retrieve something.",
    "hopping": "Jumping on one leg, with alternate leg lifts.",
    "jump up": "Pushing off the ground with both feet, body rising upward.",
    "phone call": "Holding phone near ear, speaking or listening.",
    "play with phone or tablet": "Using fingers to swipe or tap on a screen.",
    "type on keyboard": "Moving fingers over keys, pressing them in rapid sequence.",
    "point at something": "Extending arm with finger pointing towards an object.",
    "taking photo": "Holding a camera or phone, pressing button to capture an image.",
    "check time from watch": "Turning wrist to face watch, glancing at time.",
    "rub two hands": "Rubbing palms together in a fast motion.",
    "nod head or bow": "Moving head up and down or tilting forward.",
    "shake head": "Moving head side to side to indicate negation.",
    "wipe face": "Using hand or cloth to rub or wipe the face.",
    "salute": "Raising hand to forehead in a formal greeting gesture.",
    "put palms together": "Bringing hands together in front of chest, palms touching.",
    "cross hands in front": "Crossing arms over chest or body.",
    "sneeze or cough": "Forceful expulsion of air from the mouth or nose.",
    "staggering": "Walking unsteadily, with uneven steps or loss of balance.",
    "falling down": "Sudden drop to the ground, typically after losing balance.",
    "headache": "Holding head with hands, indicating discomfort.",
    "chest pain": "Pressing hands over chest, indicating pain or discomfort.",
    "back pain": "Arching back or pressing hands against lower back.",
    "neck pain": "Cringing or tilting head due to neck discomfort.",
    "nausea or vomiting": "Making gagging or retching motions with the body.",
    "fan self": "Waving hand or using an object to create air movement.",
    "punch or slap": "Swinging arm rapidly to strike an object or person.",
    "kicking": "Lifting leg and extending foot forward to strike.",
    "pushing": "Shoving or forcing an object away with hands or arms.",
    "pat on back": "Gently tapping or patting the back with a hand.",
    "point finger": "Extending finger to point towards something or someone.",
    "hugging": "Wrapping arms around another person in a close embrace.",
    "giving object": "Extending hand to offer an object to someone.",
    "touch pocket": "Placing hand in pocket or feeling around in the pocket.",
    "shaking hands": "Grasping and moving hands up and down in greeting.",
    "walking towards": "Taking steps forward in the direction of a target.",
    "walking apart": "Moving away from each other, stepping in opposite directions."
}

pku51_motion_descriptions = {
    'bow': "Bending the upper body forward at the waist, usually to show respect.",
    'brushing hair': "Moving a brush or comb through the hair, typically with a back-and-forth motion.",
    'brushing teeth': "Using a toothbrush to scrub teeth, typically in circular or up-and-down movements.",
    'check time (from watch)': "Turning wrist to look at a watch, raising hand to eye level.",
    'cheer up': "Raising arms or clapping in a joyful or enthusiastic manner.",
    'clapping': "Bringing both hands together in a rhythmic motion, creating sound.",
    'cross hands in front (say stop)': "Crossing arms over the chest or in front of the body, often with a stop gesture.",
    'drink water': "Lifting hand to mouth, tilting wrist to drink from a bottle or glass.",
    'drop': "Letting an object fall from the hands, with downward motion.",
    'eat meal/snack': "Bringing food to the mouth, with hand or utensil, followed by chewing motions.",
    'falling': "Losing balance and dropping quickly to the ground, body moving downward.",
    'giving something to other person': "Extending hand to offer or pass an object to another person.",
    'hand waving': "Moving the hand back and forth, usually in greeting or farewell.",
    'handshaking': "Extending a hand towards another person and grasping their hand, shaking it up and down.",
    'hopping (one foot jumping)': "Jumping on one leg, lifting and lowering the body with a repeated motion.",
    'hugging other person': "Wrapping arms around another person in a close, comforting embrace.",
    'jump up': "Pushing off the ground with both feet, causing the body to rise into the air.",
    'kicking other person': "Lifting leg and extending foot to strike another person, usually with force.",
    'kicking something': "Lifting leg and striking an object with the foot, typically in a forward motion.",
    'make a phone call/answer phone': "Holding the phone to the ear, with motion of the hand to answer or dial.",
    'pat on back of other person': "Gently tapping the back of another person with an open hand.",
    'pickup': "Bending down or reaching to grasp an object, typically lifting it back up.",
    'playing with phone/tablet': "Touching or swiping the screen, interacting with the device using fingers.",
    'point finger at the other person': "Extending finger and pointing in the direction of another person.",
    'pointing to something with finger': "Extending the finger towards an object or location.",
    'punching/slapping other person': "Swinging arm to strike another person, with force and speed.",
    'pushing other person': "Using hands or arms to apply force and move another person.",
    'put on a hat/cap': "Placing a hat or cap on the head, adjusting for fit.",
    'put something inside pocket': "Sliding an object into a pocket using one or both hands.",
    'reading': "Flipping through pages or scrolling with fingers, reading text.",
    'rub two hands together': "Rubbing palms or fingers together rapidly to generate heat.",
    'salute': "Raising hand to forehead or to the side of the head in a formal gesture.",
    'sitting down': "Lowering the body to a seated position, bending knees and hips.",
    'standing up': "Rising from a seated position, using legs and torso to push up.",
    'take off a hat/cap': "Lifting hat or cap from the head, removing it with one hand.",
    'take off glasses': "Grasping glasses from the face and lifting them off.",
    'take off jacket': "Slipping out of sleeves and removing the jacket from the body.",
    'take out something from pocket': "Reaching into a pocket and pulling out an object.",
    'taking a selfie': "Holding a phone or camera at arm's length and pressing a button to capture an image.",
    'tear up paper': "Grabbing paper with hands and pulling it apart, usually with a tearing motion.",
    'throw': "Swinging arm forward to release an object with force and motion.",
    'touch back (backache)': "Pressing hand against the back or rubbing to relieve pain.",
    'touch chest (stomachache/heart pain)': "Placing hand on chest, often to indicate discomfort or pain.",
    'touch head (headache)': "Placing hand on the head, usually to express pain or pressure.",
    'touch neck (neckache)': "Gently massaging or pressing on the neck to relieve discomfort.",
    'typing on a keyboard': "Using fingers to press keys on a keyboard in quick, repetitive motions.",
    'use a fan (with hand or paper)/feeling warm': "Moving hand or paper back and forth to create airflow, indicating heat.",
    'wear jacket': "Putting on a jacket by slipping arms through the sleeves and adjusting it over the shoulders.",
    'wear on glasses': "Placing glasses over the eyes and adjusting them for fit.",
    'wipe face': "Using hand or cloth to gently rub or wipe the face.",
    'writing': "Moving a pen or pencil across paper, forming letters or symbols."
}

ntu120_motion_descriptions = {
    'drink water': "Lifting hand to mouth, tilting wrist to drink from a bottle or glass.",
    'eat meal': "Bringing food to mouth, with hand or utensil, followed by chewing motion.",
    'brush teeth': "Using a toothbrush to scrub teeth, typically in circular or up-and-down movements.",
    'brush hair': "Moving a brush or comb through the hair, typically with a back-and-forth motion.",
    'drop': "Letting an object fall from the hands, with downward motion.",
    'pick up': "Bending down or reaching to grasp an object, typically lifting it back up.",
    'throw': "Swinging arm forward to release an object with force and motion.",
    'sit down': "Lowering the body to a seated position, bending knees and hips.",
    'stand up': "Rising from a seated position, using legs and torso to push up.",
    'clapping': "Bringing both hands together in a rhythmic motion, creating sound.",
    'reading': "Flipping through pages or scrolling with fingers, reading text.",
    'writing': "Moving a pen or pencil across paper, forming letters or symbols.",
    'tear up paper': "Grabbing paper with hands and pulling it apart, usually with a tearing motion.",
    'put on jacket': "Sliding arms into sleeves, adjusting the jacket over the body.",
    'take off jacket': "Removing arms from sleeves, pulling jacket off shoulders.",
    'put on shoe': "Bending down, placing feet into shoes, and adjusting.",
    'take off shoe': "Sliding feet out of shoes, typically in an upward motion.",
    'put on glasses': "Lifting glasses and placing them on the face.",
    'take off glasses': "Removing glasses from the face, pulling them away from eyes.",
    'put on hat or cap': "Placing hat on the head, adjusting it.",
    'take off hat or cap': "Removing hat from the head, lifting it off.",
    'cheer up': "Raising arms or clapping in a joyful or enthusiastic manner.",
    'hand waving': "Moving the hand back and forth, usually in greeting or farewell.",
    'kicking something': "Lifting leg and striking an object with the foot.",
    'reach into pocket': "Extending arm and hand into the pocket to retrieve something.",
    'hopping': "Jumping on one leg, with alternate leg lifts.",
    'jump up': "Pushing off the ground with both feet, body rising upward.",
    'phone call': "Holding phone near ear, speaking or listening.",
    'play with phone or tablet': "Using fingers to swipe or tap on a screen.",
    'type on keyboard': "Moving fingers over keys, pressing them in rapid sequence.",
    'point at something': "Extending arm with finger pointing towards an object.",
    'taking photo': "Holding a camera or phone, pressing button to capture an image.",
    'check time from watch': "Turning wrist to face watch, glancing at time.",
    'rub two hands': "Rubbing palms together in a fast motion.",
    'nod head or bow': "Moving head up and down or tilting forward.",
    'shake head': "Moving head side to side to indicate negation.",
    'wipe face': "Using hand or cloth to rub or wipe the face.",
    'salute': "Raising hand to forehead in a formal greeting gesture.",
    'put palms together': "Bringing hands together in front of chest, palms touching.",
    'cross hands in front': "Crossing arms over chest or body.",
    'sneeze or cough': "Forceful expulsion of air from the mouth or nose.",
    'staggering': "Walking unsteadily, with uneven steps or loss of balance.",
    'falling down': "Sudden drop to the ground, typically after losing balance.",
    'headache': "Holding head with hands, indicating discomfort.",
    'chest pain': "Pressing hands over chest, indicating pain or discomfort.",
    'back pain': "Arching back or pressing hands against lower back.",
    'neck pain': "Cringing or tilting head due to neck discomfort.",
    'nausea or vomiting': "Making gagging or retching motions with the body.",
    'fan self': "Waving hand or using an object to create air movement.",
    'punch or slap': "Swinging arm rapidly to strike an object or person.",
    'kicking': "Lifting leg and extending foot forward to strike.",
    'pushing': "Shoving or forcing an object away with hands or arms.",
    'pat on back': "Gently tapping or patting the back with a hand.",
    'point finger': "Extending finger to point towards something or someone.",
    'hugging': "Wrapping arms around another person in a close embrace.",
    'giving object': "Extending hand to offer an object to someone.",
    'touch pocket': "Placing hand in pocket or feeling around in the pocket.",
    'shaking hands': "Grasping and moving hands up and down in greeting.",
    'walking towards': "Taking steps forward in the direction of a target.",
    'walking apart': "Moving away from each other, stepping in opposite directions.",
    'put on headphone': "Placing headphones over ears, adjusting for fit.",
    'take off headphone': "Removing headphones from ears, lifting them off.",
    'shoot at basket': "Throwing a basketball towards the hoop, aiming with arm.",
    'bounce ball': "Bouncing a ball on the ground by using a repetitive hand motion.",
    'tennis bat swing': "Swinging a tennis racket with force to hit a ball.",
    'juggle table tennis ball': "Tossing and catching a small ball in the air with alternate hands.",
    'hush': "Making a gesture with hand or finger to indicate quiet.",
    'flick hair': "Lightly pushing hair out of face by flipping or swiping it with hand.",
    'thumb up': "Raising thumb upwards in a positive gesture.",
    'thumb down': "Lowering thumb downwards in a negative gesture.",
    'make ok sign': "Forming a circle with thumb and index finger, other fingers extended.",
    'make victory sign': "Raising two fingers in a ‘V’ shape, often indicating victory.",
    'staple book': "Pressing a stapler to attach pages together in a book.",
    'counting money': "Holding bills or coins and physically counting them with fingers.",
    'cutting nails': "Using clippers or scissors to trim nails, clipping off small portions.",
    'cutting paper': "Using scissors or knife to cut paper in a specific shape or size.",
    'snap fingers': "Creating a sharp sound by pressing thumb and middle finger together and releasing quickly.",
    'open bottle': "Twisting or pulling off a bottle cap to open it.",
    'sniff or smell': "Inhaling through nose to detect a scent.",
    'squat down': "Bending knees and lowering body while keeping feet flat.",
    'toss coin': "Flipping a coin into the air with fingers, typically a light upward motion.",
    'fold paper': "Bending paper along a crease to make a fold.",
    'ball up paper': "Rolling a piece of paper into a tight ball with hands.",
    'play magic cube': "Twisting and turning the sides of a Rubik's cube to align colors.",
    'apply cream on face': "Gently rubbing or dabbing cream on the face with hands.",
    'apply cream on hand': "Applying lotion or cream to the hands by rubbing together.",
    'put on bag': "Placing a bag over the shoulder or carrying it in hand.",
    'take off bag': "Removing the bag from the shoulder or hand.",
    'put object into bag': "Placing an object inside a bag, often using hand.",
    'take object out bag': "Removing an object from a bag, typically with hands.",
    'open box': "Lifting or pulling a lid off a box to open it.",
    'move heavy objects': "Using force to push or pull a heavy object.",
    'shake fist': "Shaking a closed fist, often in anger or frustration.",
    'throw up cap or hat': "Throwing a cap or hat into the air.",
    'capitulate': "Surrendering by raising hands or body in a yielding gesture.",
    'cross arms': "Placing arms across the chest, typically in a defensive posture.",
    'arm circles': "Moving arms in circular motions, typically to warm up.",
    'arm swings': "Swinging arms back and forth from the shoulders.",
    'run on the spot': "Running in place by quickly alternating foot movements.",
    'butt kicks': "Kicking buttocks with the heels while running in place.",
    'cross toe touch': "Touching opposite hand to toe, crossing body midline.",
    'side kick': "Lifting leg sideways and extending it to strike.",
    'yawn': "Opening mouth wide and inhaling deeply, typically when tired.",
    'stretch oneself': "Stretching arms or legs to increase flexibility.",
    'blow nose': "Exhaling forcefully through the nose to clear it.",
    'hit with object': "Striking something with a physical object.",
    'wield knife': "Holding a knife and using it for cutting or other purposes.",
    'knock over': "Pushing an object to topple it.",
    'grab stuff': "Grabbing objects with hands or fingers.",
    'shoot with gun': "Pointing and firing a gun, releasing bullets.",
    'step on foot': "Placing foot down on another person’s foot.",
    'high five': "Slapping hands together in celebration or greeting.",
    'drink after cheers': "Raising a glass to toast and drinking after clinking.",
    'carry object': "Holding an object while walking or moving.",
    'take photo': "Holding a camera or phone, pressing the button to capture an image.",
    'follow': "Walking or moving behind someone.",
    'whisper': "Speaking in a soft voice close to someone's ear.",
    'exchange things': "Handing something to another person and receiving something in return.",
    'support somebody': "Helping or providing physical support to another person.",
    'rock paper scissors': "Performing hand gestures representing rock, paper, or scissors, followed by a decision."
}

ntu60_shape_descriptions = {
    'drink water': "Body remains upright, arm extends towards mouth, elbow slightly bent, head remains neutral.",
    'eat meal': "Body leans slightly forward, elbows bend as the hand brings food to mouth, torso remains steady.",
    'brush teeth': "Head leans slightly forward, arms move in circular or up-and-down motions near the mouth, posture stays upright.",
    'brush hair': "Head remains still or tilts slightly, arms extend to brush hair, body stays mostly upright.",
    'drop': "Hand opens, fingers relax, wrist drops the object, body remains neutral or upright.",
    'pick up': "Knees bend, arm reaches toward the object on the ground, torso and legs engage to lift it.",
    'throw': "Arm swings backward, then extends forward in a fast motion, body may slightly rotate for momentum.",
    'sit down': "Knees bend deeply, hips lower, feet remain flat on the ground, back remains relatively straight.",
    'stand up': "Legs straighten, feet push off the ground, torso remains upright while standing.",
    'clapping': "Arms extend outward, both hands strike together, elbows slightly bent, shoulders relaxed.",
    'reading': "Body remains relatively still, eyes focus on the text, hands hold a book or device, head may tilt slightly.",
    'writing': "Arms move actively, fingers grip pen/pencil, body stays upright as hands move to write.",
    'tear up paper': "Hands grip paper, arms bend to pull it apart, body stays upright or slightly leans forward.",
    'put on jacket': "Arms extend through sleeves, body leans slightly forward or backward to adjust the jacket.",
    'take off jacket': "Arms move out of the sleeves, torso and arms rotate to remove the jacket.",
    'put on shoe': "Body bends slightly, one leg lifts to insert foot into the shoe, back remains upright.",
    'take off shoe': "Foot lifts and slips out of the shoe, back remains straight, body stays upright.",
    'put on glasses': "Hands reach up to position glasses on the face, head remains still or tilts slightly.",
    'take off glasses': "Fingers grip the sides of the glasses, hand moves to gently remove them, head may lean forward slightly.",
    'put on hat or cap': "Arms lift hat or cap towards the head, hands position it, head stays neutral.",
    'take off hat or cap': "Hands grasp the hat or cap, move it away from the head, body stays neutral.",
    'cheer up': "Arms raise and extend upward, body stretches vertically, shoulders back, head lifted.",
    'hand waving': "Arm moves back and forth, elbow bent, wrist relaxed, body remains upright or neutral.",
    'kicking something': "One leg extends forward or sideways with force, body maintains upright posture.",
    'reach into pocket': "Arm extends to the side, hand moves into the pocket, body slightly leans forward.",
    'hopping': "One leg lifts and the other leg supports, body moves upward and downward in quick succession.",
    'jump up': "Both feet push off the ground, legs extend, arms may lift for momentum, body moves vertically.",
    'phone call': "One hand holds the phone to the ear, other hand may be relaxed at the side, body upright.",
    'play with phone or tablet': "Hands hold the device, fingers interact with the screen, body remains relaxed or slightly leaned forward.",
    'type on keyboard': "Arms and hands move over the keys, fingers press each key rapidly, body remains upright.",
    'point at something': "Arm extends with the index finger pointing, torso may twist slightly to direct attention.",
    'taking photo': "Hands hold a camera or phone, arms extend slightly, body remains stable.",
    'check time from watch': "Wrist turns upwards, fingers may support or move slightly, head tilts downward toward the watch.",
    'rub two hands': "Both hands move together, rubbing gently, arms remain close to the body.",
    'nod head or bow': "Head moves up and down or tilts forward in a bowing gesture, body remains neutral or slightly bent forward.",
    'shake head': "Head moves gently from side to side, body stays upright.",
    'wipe face': "Hand or cloth moves over the face, body may tilt slightly in the direction of the motion.",
    'salute': "Right hand moves towards the forehead, arm extends with a sharp motion, body stays upright.",
    'put palms together': "Hands come together in front of the chest, elbows bent, body remains neutral.",
    'cross hands in front': "Arms cross over the chest, shoulders and elbows engage in the motion, body may lean slightly.",
    'sneeze or cough': "Upper body leans slightly forward, mouth and nose expel air forcefully.",
    'staggering': "Body sways from side to side, steps are unstable, head may tilt slightly.",
    'falling down': "Body loses balance and descends, legs bend to absorb the impact, arms may flail.",
    'headache': "Hands press against the head, body leans slightly or stays still, facial expression shows discomfort.",
    'chest pain': "Hands press against the chest, body may lean or slouch forward slightly.",
    'back pain': "Hands hold or support the back, upper body bends slightly to relieve pressure.",
    'neck pain': "Hand touches the neck for relief, head may tilt or rotate gently.",
    'nausea or vomiting': "Body may lean forward, hands cover the mouth, face shows discomfort.",
    'fan self': "Arm moves or an object is used to fan oneself, body may sway or shift slightly.",
    'punch or slap': "Arm extends forward with a fist or open hand, body may rotate or bend for force.",
    'kicking': "Leg extends with force, foot strikes an object, body remains upright.",
    'pushing': "Arms push an object forward or to the side, body may lean slightly into the action.",
    'pat on back': "One hand gently pats the back of another person, arm bends at the elbow.",
    'point finger': "Index finger extends and points, arm remains mostly extended, body stays neutral.",
    'hugging': "Arms wrap around another person, torso may lean forward or to one side.",
    'giving object': "Hands extend towards the other person, arm straightens, body may lean slightly forward.",
    'touch pocket': "Hand reaches for the pocket, body may lean forward slightly.",
    'shaking hands': "Two hands meet in a handshake, arms extend, bodies stay facing each other.",
    'walking towards': "Body moves in the direction of the target, legs stretch naturally.",
    'walking apart': "Body moves in opposite directions, legs step forward, body remains balanced."
}

pku51_shape_descriptions = {
    'bow': "Upper body bends forward from the waist, head lowers slightly, arms may hang loosely or extend outward.",
    'brushing hair': "One arm moves to brush hair, head may tilt slightly to the side, body remains upright.",
    'brushing teeth': "Head leans slightly forward, arms move in small circular or up-and-down motions near the mouth, torso remains steady.",
    'check time (from watch)': "Wrist rotates upwards, hand supports or holds watch, head may tilt downward to check the time.",
    'cheer up': "Arms raise above the head in a celebratory motion, chest open, body stretches vertically.",
    'clapping': "Both hands meet in front of the chest or above, arms extend with elbows slightly bent, body stays relaxed.",
    'cross hands in front (say stop)': "Arms cross over the chest, body may rotate slightly to the side, elbows bend in front of the body.",
    'drink water': "Arm extends towards the mouth with the glass, head remains upright, elbows slightly bent.",
    'drop': "Hand opens, fingers release an object, wrist drops, body remains neutral.",
    'eat meal/snack': "Torso leans slightly forward, elbows bend to bring food to mouth, head follows the motion.",
    'falling': "Body loses balance and descends quickly, legs bend or flail, arms may be raised or outstretched to protect.",
    'giving something to other person': "Arm extends forward with an object, body may lean slightly toward the recipient.",
    'hand waving': "Arm moves back and forth in the air, wrist relaxed, body remains upright.",
    'handshaking': "Two hands meet, palms touch, fingers clasp or interlock, arms extend towards each other.",
    'hopping (one foot jumping)': "One leg lifts and propels the body upwards while the other leg supports, body moves rapidly upward and downward.",
    'hugging other person': "Arms wrap around the other person’s torso, body leans slightly forward or to one side.",
    'jump up': "Both feet push off the ground, legs extend, arms may lift for momentum, body moves vertically.",
    'kicking other person': "One leg extends forcefully toward the target, body remains balanced, arms may move for stabilization.",
    'kicking something': "Leg extends with force, foot strikes an object, body stays upright or may slightly rotate.",
    'make a phone call/answer phone': "One hand holds the phone to the ear, the other hand may rest at the side or hold the phone, body remains upright.",
    'pat on back of other person': "One hand pats the other person’s back, arm may extend fully or slightly bend, body remains neutral.",
    'pickup': "Legs bend to lower the body, one or both hands reach down to lift an object, body stays centered.",
    'playing with phone/tablet': "Hands hold the phone or tablet, fingers interact with the screen, body may lean slightly forward.",
    'point finger at the other person': "Arm extends with the index finger pointing, torso may twist slightly to direct attention.",
    'pointing to something with finger': "Index finger extends toward the object, arm may bend slightly, body remains neutral.",
    'punching/slapping other person': "Arm extends with a fist or open hand, body rotates or shifts weight for force, other hand may stabilize the body.",
    'pushing other person': "Arm extends forward, palm presses against the other person, body may lean slightly into the push.",
    'put on a hat/cap': "Arms raise to position the hat or cap on the head, body remains upright, head slightly tilted.",
    'put something inside pocket': "Arm extends to the side, hand moves into the pocket, body may lean forward slightly.",
    'reading': "Body stays upright, hands hold a book or device, eyes focus on the text, head may tilt slightly.",
    'rub two hands together': "Both hands move together in a rubbing motion, arms stay close to the body.",
    'salute': "Right hand moves to the forehead, arm extends in a sharp motion, body stays upright.",
    'sitting down': "Knees bend, hips lower, feet remain flat on the ground, body stays centered.",
    'standing up': "Legs straighten, feet push off the ground, body returns to an upright position.",
    'take off a hat/cap': "Hands grasp the hat or cap, move it away from the head, body remains neutral.",
    'take off glasses': "Fingers grip the glasses, hands remove them from the face, head stays steady.",
    'take off jacket': "Arms move out of the sleeves, body rotates or leans slightly for easier removal.",
    'take out something from pocket': "Arm extends toward the pocket, hand reaches inside, body may tilt slightly to assist the motion.",
    'taking a selfie': "Arm extends holding the phone or camera, body faces the camera, one or both hands may be positioned to stabilize.",
    'tear up paper': "Hands grip the paper, arms bend to pull it apart, torso stays upright or leans slightly forward.",
    'throw': "Arm swings backward, then extends forward with force, body may rotate slightly for momentum.",
    'touch back (backache)': "Hands press against the back, body may lean forward or slightly twist in discomfort.",
    'touch chest (stomachache/heart pain)': "Hands press on the chest or stomach, body may lean slightly forward or twist.",
    'touch head (headache)': "Hands gently press against the forehead or temples, body remains upright.",
    'touch neck (neckache)': "One hand gently presses against the neck, head may tilt slightly to the side.",
    'typing on a keyboard': "Arms and hands move over the keyboard, fingers press keys, body remains upright or slightly leaned forward.",
    'use a fan (with hand or paper)/feeling warm': "Arm moves in a fanning motion, body may sway slightly as the fan is used.",
    'wear jacket': "Arms extend into the sleeves, body rotates or leans slightly to adjust the jacket.",
    'wear on glasses': "Hands lift glasses to position them on the face, head may tilt slightly forward.",
    'wipe face': "One or both hands move across the face, body may tilt slightly or remain neutral.",
    'writing': "Arms move actively with a pen or pencil, fingers grip writing instrument, body remains upright."
}

ntu120_shape_descriptions = {
    'drink water': "Arm bends, hand lifts to mouth, body remains upright.",
    'eat meal': "Arm brings food to mouth, body slightly leans forward, elbows and torso slightly bend.",
    'brush teeth': "Upper body leans slightly forward, arms move in circular or up-and-down motions near the mouth and face.",
    'brush hair': "Arms move around the head in back-and-forth motions, head remains upright or slightly turns.",
    'drop': "Wrist relaxes, hand releases the object, body remains upright or standing.",
    'pick up': "Bend knees and lower body while keeping feet flat, arms extend towards the object.",
    'throw': "Arm swings backward, then quickly extends forward, shoulder and wrist generate power, legs bend slightly for more momentum.",
    'sit down': "Gradually bend knees from standing, hips lower while knees and hips remain aligned.",
    'stand up': "From sitting, use leg strength to rise vertically, maintaining straight back and knees.",
    'clapping': "Both hands strike together forcefully, elbows slightly bent, shoulders relaxed.",
    'reading': "Hands hold a book or device, eyes focus on the text, body remains stable or slightly leans forward.",
    'writing': "Wrists and fingers move actively, arms shift while keeping the body upright.",
    'tear up paper': "Hands reach for the paper and tear it forcefully, shoulders and wrists engaged, body stays upright.",
    'put on jacket': "Arms extend through sleeves, body leans forward slightly to zip or button up.",
    'take off jacket': "Arms pull out from the sleeves, body slightly leans forward or backward to remove the jacket.",
    'put on shoe': "Bend knees, lift one foot and place the shoe on, keeping the back straight.",
    'take off shoe': "Lift foot, slide shoe off, back remains upright.",
    'put on glasses': "Lift glasses with hands, arms extend, eyes focused forward.",
    'take off glasses': "Use fingers to grasp the sides of the glasses, gently remove from face, head slightly tilts forward.",
    'put on hat or cap': "Hands reach for the hat or cap and place it on the head, head stays upright.",
    'take off hat or cap': "One hand grips the edge of the hat or cap, gently removes it, head stays natural.",
    'cheer up': "Arms raised high, shoulders and arms stretched, body slightly extends upwards showing an upbeat posture.",
    'hand waving': "Wrist gently swings, elbows slightly bent, arm moves up and down or side to side.",
    'kicking something': "Leg lifts and extends sideways or forward, foot kicks out, body stays upright.",
    'reach into pocket': "Arm extends into pants or jacket pocket, body leans slightly forward.",
    'hopping': "One foot leaves the ground, other foot supports, body moves up and down.",
    'jump up': "Both feet push off the ground, legs extend, body leaps upwards.",
    'phone call': "One hand holds the phone to the ear, other hand naturally hangs or supports the phone.",
    'play with phone or tablet': "Fingers lightly tap or swipe the screen, arms stay relaxed, head tilts slightly forward.",
    'type on keyboard': "Both hands quickly press the keys, fingers extend, body stays upright.",
    'point at something': "Arm extends, index finger points at an object, body stays natural.",
    'taking photo': "Hold camera or phone, arm extends, shoulders and upper body remain stable.",
    'check time from watch': "Wrist turns up, other hand supports slightly, eyes focus on the watch.",
    'rub two hands': "Both hands rub together, arms stay close to the body, motion is relaxed.",
    'nod head or bow': "Head moves slightly up and down, or tilts forward slightly in a bow.",
    'shake head': "Head moves gently left and right, often accompanied by a negative expression.",
    'wipe face': "Hands or cloth wipe the face, arms and fingers move fluidly.",
    'salute': "Arm raises to forehead, arm extends, head stays upright.",
    'put palms together': "Hands are brought together in front of the chest, palms facing each other, elbows bent naturally.",
    'cross hands in front': "Arms cross over the chest, shoulders slightly tighten.",
    'sneeze or cough': "Upper body leans slightly forward, chest expands, mouth and nose forcefully expel air.",
    'staggering': "Body is unstable, steps are irregular, may sway back and forth or side to side.",
    'falling down': "Body loses balance and falls down, legs bend to reduce impact.",
    'headache': "Hands hold the head, brow furrows, body shows discomfort or slightly bends.",
    'chest pain': "Hands press on the chest, facial expression tense, body may lean slightly.",
    'back pain': "Upper body bends, hands press against the back, or one hand supports the back.",
    'neck pain': "Neck twists slightly or lowers, hands touch the neck for relief.",
    'nausea or vomiting': "Upper body leans forward, hands cover the mouth, face shows discomfort.",
    'fan self': "Arms swing or use an object to create airflow, body may sway slightly.",
    'punch or slap': "Arm swings forward quickly, fist or hand strikes with force, body remains upright.",
    'kicking': "Leg extends, foot strikes forward or sideways, back remains straight.",
    'pushing': "Arms push forward or to the side, body may lean slightly forward.",
    'pat on back': "Hand gently pats the back, arm slightly bent, motion is light.",
    'point finger': "Index finger extends toward an object or person, elbow and shoulder relaxed.",
    'hugging': "Arms wrap around another person, body leans forward or toward one side.",
    'giving object': "Hands extend to give an object, arms straighten, body leans slightly forward.",
    'touch pocket': "Hand reaches into the pocket, body leans slightly forward.",
    'shaking hands': "Both hands grasp and shake, body stays natural standing.",
    'walking towards': "Body moves towards a target, legs stretch naturally.",
    'walking apart': "Move in opposite directions, steps stable, body rotates accordingly.",
    'put on headphone': "Arms raise the headphones and place them on the ears, head slightly tilts.",
    'take off headphone': "Hands lift the headphones and remove them, head tilts slightly backward.",
    'shoot at basket': "Arms throw an object, feet push off the ground, body slightly bends for more power.",
    'bounce ball': "Hands repeatedly tap the ball, ball bounces on the ground.",
    'tennis bat swing': "Arm swings the racket, shoulders rotate with the motion.",
    'juggle table tennis ball': "Hands alternate to keep the ball in the air.",
    'hush': "Hand gesture or finger to lips signaling quiet, arms stay relaxed.",
    'flick hair': "Hand flicks the hair, head slightly tilts, hair is brushed aside.",
    'thumb up': "Hand opens, thumb points upwards, body stays relaxed.",
    'thumb down': "Hand opens, thumb points down, body posture remains neutral.",
    'make ok sign': "Forming a circle with the thumb and index finger, body posture remains neutral.",
    'make victory sign': "Hand forms a 'V' shape with the index and middle fingers, body relaxed.",
    'staple book': "Hands press the stapler onto the book, arm extends.",
    'counting money': "Hands hold and flip through bills, fingers and wrists move.",
    'cutting nails': "Hands hold nail clippers, fingers press against the clippers, arm remains steady.",
    'cutting paper': "Hands hold scissors and paper, hands and wrists move steadily.",
    'snap fingers': "Fingers press together, thumb and middle finger quickly snap, sharp sound created.",
    'open bottle': "Twist or pull off the bottle cap, arms and hands move in a rotating motion.",
    'sniff or smell': "Inhaling through the nose, body remains neutral or slightly leans forward.",
    'squat down': "Knees bend deeply, hips lower while keeping feet flat.",
    'toss coin': "Flip coin into the air with fingers, typically light upward motion.",
    'fold paper': "Bend paper along a crease, arms and hands stay steady.",
    'ball up paper': "Roll paper into a ball, hands press together to shape it.",
    'play magic cube': "Twist and turn the sides of the cube to align colors, wrists and hands in motion.",
    'apply cream on face': "Hands gently rub or dab cream on the face.",
    'apply cream on hand': "Rub lotion or cream between hands to apply to the skin.",
    'put on bag': "Place a bag over the shoulder or carry it in hand.",
    'take off bag': "Remove bag from shoulder or hand, body remains neutral.",
    'put object into bag': "Place an object inside the bag using hands.",
    'take object out bag': "Remove object from the bag, typically with one or both hands.",
    'open box': "Lift or pull a lid off the box, arms extend.",
    'move heavy objects': "Push or pull a heavy object using force, body leans forward to provide strength.",
    'shake fist': "Raise fist and shake it, typically as a gesture of defiance or anger.",
    'throw up cap or hat': "Toss cap or hat into the air with an upward motion.",
    'capitulate': "Body slumps slightly, hands may drop to sides in surrender.",
    'cross arms': "Arms cross in front of the chest, body maintains a closed posture.",
    'arm circles': "Arms rotate in circular motions, shoulders engaged.",
    'arm swings': "Arms swing back and forth naturally, body stays relaxed.",
    'run on the spot': "Feet remain on the ground but legs rapidly move in place, arms swing naturally.",
    'butt kicks': "Legs move rapidly, feet kick toward the glutes, body stays upright.",
    'cross toe touch': "One leg crosses in front of the other, foot reaches for the opposite toe.",
    'side kick': "Leg extends sideways with force, body remains balanced and straight.",
    'yawn': "Mouth opens widely, body may stretch or lean back.",
    'stretch oneself': "Arms extend overhead, back slightly arches, body elongates.",
    'blow nose': "Hand or tissue is held to nose, body tilts forward slightly.",
    'hit with object': "Arm extends with an object in hand, body moves to strike a target.",
    'wield knife': "Grip knife with hand, arm extends or twists to use the knife.",
    'knock over': "Hand or object pushes something down, arm extends with force.",
    'grab stuff': "Hand reaches out to grab or hold an object.",
    'shoot with gun': "Arm extends forward holding the gun, body slightly leans into the shot.",
    'step on foot': "Foot moves forward and presses down onto another's foot.",
    'high five': "Two hands meet in a high-five, arms extend upwards.",
    'drink after cheers': "Lift glass to mouth after clinking, body remains relaxed.",
    'carry object': "Hands hold an object while walking, arms extend.",
    'take photo': "Camera or phone held in hands, arms extend, shoulders stable.",
    'follow': "Move in the direction of someone else, body follows their lead.",
    'whisper': "Lean in close to someone, body lowers or tilts towards the person.",
    'exchange things': "Hands pass objects back and forth, arms extend or retract.",
    'support somebody': "Body moves to assist someone else, hands may steady them.",
    'rock paper scissors': "Hands form shapes of rock, paper, or scissors, in rhythmic motions."
}

ntu60_action_rename = {
    'drink water': 'Sip Water',
    'eat meal': 'Consume Food',
    'brush teeth': 'Clean Teeth',
    'brush hair': 'Comb Hair',
    'drop': 'Let Go of Object',
    'pick up': 'Lift Object',
    'throw': 'Toss Object',
    'sit down': 'Lower to Sitting Position',
    'stand up': 'Rise to Standing Position',
    'clapping': 'Applaud',
    'reading': 'Engage in Reading',
    'writing': 'Handwriting',
    'tear up paper': 'Rip Paper',
    'put on jacket': 'Wear Jacket',
    'take off jacket': 'Remove Jacket',
    'put on shoe': 'Wear Shoe',
    'take off shoe': 'Remove Shoe',
    'put on glasses': 'Wear Glasses',
    'take off glasses': 'Remove Glasses',
    'put on hat or cap': 'Wear Hat or Cap',
    'take off hat or cap': 'Remove Hat or Cap',
    'cheer up': 'Express Joy',
    'hand waving': 'Wave Hand',
    'kicking something': 'Kick Object',
    'reach into pocket': 'Reach for Pocket',
    'hopping': 'Hop on One Foot',
    'jump up': 'Leap Upward',
    'phone call': 'Make or Receive Call',
    'play with phone or tablet': 'Interact with Mobile Device',
    'type on keyboard': 'Type on Computer',
    'point at something': 'Point to Object',
    'taking photo': 'Capture Photo',
    'check time from watch': 'Check Watch',
    'rub two hands': 'Rub Hands Together',
    'nod head or bow': 'Nod or Bow Head',
    'shake head': 'Shaking Head',
    'wipe face': 'Cleanse Face',
    'salute': 'Military Salute',
    'put palms together': 'Join Palms',
    'cross hands in front': 'Cross Arms in Front',
    'sneeze or cough': 'Cough or Sneeze',
    'staggering': 'Stumble or Sway',
    'falling down': 'Fall to Ground',
    'headache': 'Hold Head in Pain',
    'chest pain': 'Press Chest in Pain',
    'back pain': 'Hold Back in Pain',
    'neck pain': 'Touch Neck in Pain',
    'nausea or vomiting': 'Feel Nauseous or Vomit',
    'fan self': 'Fan Self for Coolness',
    'punch or slap': 'Strike with Hand',
    'kicking': 'Kick',
    'pushing': 'Push Object or Person',
    'pat on back': 'Pat on the Back',
    'point finger': 'Point with Finger',
    'hugging': 'Hug Someone',
    'giving object': 'Hand Over Object',
    'touch pocket': 'Touch Pocket Area',
    'shaking hands': 'Handshake',
    'walking towards': 'Approach',
    'walking apart': 'Separate Walking'
}

pku51_action_rename = {
    'bow': 'Bend Down',
    'brushing hair': 'Comb Hair',
    'brushing teeth': 'Clean Teeth',
    'check time (from watch)': 'Look at Watch',
    'cheer up': 'Celebrate',
    'clapping': 'Applaud',
    'cross hands in front (say stop)': 'Cross Arms',
    'drink water': 'Sip Water',
    'drop': 'Release Object',
    'eat meal/snack': 'Eat Food',
    'falling': 'Lose Balance and Fall',
    'giving something to other person': 'Give Object to Someone',
    'hand waving': 'Wave Hand',
    'handshaking': 'Handshake',
    'hopping (one foot jumping)': 'Hop on One Foot',
    'hugging other person': 'Hug Someone',
    'jump up': 'Jump Upward',
    'kicking other person': 'Kick Someone',
    'kicking something': 'Kick Object',
    'make a phone call/answer phone': 'Make or Answer Call',
    'pat on back of other person': 'Pat Someone’s Back',
    'pickup': 'Pick Up Object',
    'playing with phone/tablet': 'Use Phone or Tablet',
    'point finger at the other person': 'Point Finger at Someone',
    'pointing to something with finger': 'Point to Object with Finger',
    'punching/slapping other person': 'Punch or Slap Someone',
    'pushing other person': 'Push Someone',
    'put on a hat/cap': 'Wear Hat or Cap',
    'put something inside pocket': 'Put Object in Pocket',
    'reading': 'Read',
    'rub two hands together': 'Rub Hands Together',
    'salute': 'Salute',
    'sitting down': 'Sit Down',
    'standing up': 'Stand Up',
    'take off a hat/cap': 'Remove Hat or Cap',
    'take off glasses': 'Remove Glasses',
    'take off jacket': 'Remove Jacket',
    'take out something from pocket': 'Take Object from Pocket',
    'taking a selfie': 'Take Selfie',
    'tear up paper': 'Tear Paper',
    'throw': 'Throw Object',
    'touch back (backache)': 'Touch Back in Pain',
    'touch chest (stomachache/heart pain)': 'Touch Chest in Pain',
    'touch head (headache)': 'Touch Head in Pain',
    'touch neck (neckache)': 'Touch Neck in Pain',
    'typing on a keyboard': 'Type on Keyboard',
    'use a fan (with hand or paper)/feeling warm': 'Use Fan or Feel Warm',
    'wear jacket': 'Put on Jacket',
    'wear on glasses': 'Put on Glasses',
    'wipe face': 'Cleanse Face',
    'writing': 'Write'

}

ntu60_classes_names = list(ntu60_motion_descriptions.keys())
pku51_classes_names = list(pku51_motion_descriptions.keys())
ntu120_classes_names = list(ntu120_motion_descriptions.keys())

ntu60_classes_rename = list(ntu60_action_rename.values())
pku51_classes_rename = list(pku51_action_rename.values())

pku51_classes_description = [f'{k} ({v})' for k, v in pku51_motion_descriptions.items()]
ntu60_classes_description = [f'{k} ({v})' for k, v in ntu60_motion_descriptions.items()]

ntu51_classes_names = list(['nod head or bow', 'brush hair', 'brush teeth', 'check time from watch', 'cheer up',
                            'clapping', 'cross hands in front', 'drink water', 'drop', 'eat meal', 'falling down',
                            'giving object', 'hand waving', 'shaking hands', 'hopping', 'hugging', 'jump up',
                            'kicking', 'kicking something', 'phone call', 'pat on back', 'pick up',
                            'play with phone or tablet', 'point finger', 'point at something',
                            'punch or slap', 'pushing', 'put on hat or cap', 'touch pocket', 'reading',
                            'rub two hands', 'salute', 'sit down', 'stand up', 'take off hat or cap',
                            'take off glasses', 'take off jacket', 'reach into pocket', 'taking photo',
                            'tear up paper', 'throw', 'back pain', 'chest pain', 'headache', 'neck pain',
                            'type on keyboard', 'fan self', 'put on jacket', 'put on glasses', 'wipe face', 'writing'])

ntu2sbu_classes_names = list(['walking towards', 'walking apart', 'kicking', 'pushing', 'shaking hands',
                              'hugging', 'giving object', 'punch or slap'])

ntu2kinetics_classes_names = list(['drink water', 'eat meal', 'brush teeth', 'brush hair', 'clapping', 'reading',
 'kicking something', 'writing', 'shake head', 'punch or slap', 'hugging',
 'shaking hands'])
if __name__ == '__main__':
    # print(pku51_classes_names)
    # ntu51_classes_names = np.load('/data/wangkun/project/datasets/NTU_dataset/ntu/ntu2pkummd/label_list.npy')
    # print(ntu51_classes_names)
    # ntu2sbu = np.load('/data/wangkun/project/datasets/NTU_dataset/ntu/ntu2sbu/label_list.npy', allow_pickle=True)
    # print(ntu2sbu)
    # ntu2kinetics = np.load('/data/wangkun/project/datasets/NTU_dataset/ntu/ntu2kinetics/label_list.npy', allow_pickle=True)
    # print(ntu2kinetics)

    n12 = [3, 5, 9, 12, 15, 40, 42, 47, 51, 56, 58, 59]
    ntu_n12 = [ntu60_classes_names[i] for i in n12]
    print(ntu_n12)